//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lector
    {
        public long ID_lector { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public Nullable<long> ID_faculty { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
