//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public long ID_lesson { get; set; }
        public Nullable<long> ID_subject { get; set; }
        public Nullable<long> ID_lector { get; set; }
        public Nullable<long> ID_course { get; set; }
        public Nullable<int> RoomNr { get; set; }
        public Nullable<System.DateTime> LessonDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Lector Lector { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
