//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UniversityExampleEntities : DbContext
    {
        public UniversityExampleEntities()
            : base("name=UniversityExampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Lector> Lector { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
    
        public virtual ObjectResult<GetStudentsByFaculty_Result> GetStudentsByFaculty(string faculty)
        {
            var facultyParameter = faculty != null ?
                new ObjectParameter("faculty", faculty) :
                new ObjectParameter("faculty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsByFaculty_Result>("GetStudentsByFaculty", facultyParameter);
        }
    
        public virtual ObjectResult<GetStudentsByFilter_Result> GetStudentsByFilter(string inputValue)
        {
            var inputValueParameter = inputValue != null ?
                new ObjectParameter("inputValue", inputValue) :
                new ObjectParameter("inputValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsByFilter_Result>("GetStudentsByFilter", inputValueParameter);
        }
    }
}
